<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="355.979" tests="8" failures="3">
  <testsuite name="Root Suite" timestamp="2020-06-26T21:07:53" tests="0" file="cypress/integration/apps/sample_sets/LM59c.js" failures="0" time="0">
  </testsuite>
  <testsuite name="59c - archive worksheets with multiple sample protocols" timestamp="2020-06-26T21:07:53" tests="8" failures="3" time="355.979">
    <testcase name="59c - archive worksheets with multiple sample protocols LM-59c-1 - Archive after all samples are complete" time="95.42" classname="LM-59c-1 - Archive after all samples are complete">
    </testcase>
    <testcase name="59c - archive worksheets with multiple sample protocols LM-59c-2 - Archive after failing all samples in the second protocol" time="25.585" classname="LM-59c-2 - Archive after failing all samples in the second protocol">
    </testcase>
    <testcase name="59c - archive worksheets with multiple sample protocols LM-59c-3 - Archive after failing first 3 samples in the second protocol" time="0" classname="LM-59c-3 - Archive after failing first 3 samples in the second protocol">
      <failure message="Timed out retrying: Expected to find element: &apos;.ag-selection-checkbox:not(.ag-hidden)&apos;, but never found it. Queried from element: &lt;div.ag-row.ag-row-no-focus.ag-row-odd.ag-row-level-0.ag-row-position-absolute&gt;" type="CypressError"><![CDATA[CypressError: Timed out retrying: Expected to find element: '.ag-selection-checkbox:not(.ag-hidden)', but never found it. Queried from element: <div.ag-row.ag-row-no-focus.ag-row-odd.ag-row-level-0.ag-row-position-absolute>
    at cypressErr (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:138036:9)
    at throwErr (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:137969:11)
    at Object.throwErrByPath (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:138017:3)
    at retry (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:132299:19)
    at onFailFn (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:120514:16)
    at tryCatcher (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:164895:23)
    at Promise._settlePromiseFromHandler (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:162831:31)
    at Promise._settlePromise (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:162888:18)
    at Promise._settlePromise0 (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:162933:10)
    at Promise._settlePromises (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:163008:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:159620:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:159630:10)
    at Async.drainQueues (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:159504:14)]]></failure>
    </testcase>
    <testcase name="59c - archive worksheets with multiple sample protocols LM-59c-4 - Archive after failing last 3 samples in the second protocol" time="0" classname="LM-59c-4 - Archive after failing last 3 samples in the second protocol">
      <failure message="Timed out retrying: Expected to find element: &apos;.ag-selection-checkbox:not(.ag-hidden)&apos;, but never found it. Queried from element: &lt;div.ag-row.ag-row-no-focus.ag-row-even.ag-row-level-0.ag-row-position-absolute.ag-row-first&gt;" type="CypressError"><![CDATA[CypressError: Timed out retrying: Expected to find element: '.ag-selection-checkbox:not(.ag-hidden)', but never found it. Queried from element: <div.ag-row.ag-row-no-focus.ag-row-even.ag-row-level-0.ag-row-position-absolute.ag-row-first>
    at cypressErr (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:138036:9)
    at throwErr (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:137969:11)
    at Object.throwErrByPath (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:138017:3)
    at retry (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:132299:19)
    at onFailFn (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:120514:16)
    at tryCatcher (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:164895:23)
    at Promise._settlePromiseFromHandler (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:162831:31)
    at Promise._settlePromise (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:162888:18)
    at Promise._settlePromise0 (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:162933:10)
    at Promise._settlePromises (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:163008:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:159620:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:159630:10)
    at Async.drainQueues (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:159504:14)]]></failure>
    </testcase>
    <testcase name="59c - archive worksheets with multiple sample protocols LM-59c-5 - Archive after failing all samples in the third protocol" time="35.624" classname="LM-59c-5 - Archive after failing all samples in the third protocol">
    </testcase>
    <testcase name="59c - archive worksheets with multiple sample protocols LM-59c-6 - Archive after first sample in the third protocol" time="56.193" classname="LM-59c-6 - Archive after first sample in the third protocol">
    </testcase>
    <testcase name="59c - archive worksheets with multiple sample protocols LM-59c-7 - Archive after last sample in the third protocol" time="56.627" classname="LM-59c-7 - Archive after last sample in the third protocol">
    </testcase>
    <testcase name="59c - archive worksheets with multiple sample protocols LM-59c-8 - Archive after failing all samples in the fourth protocol" time="43.265" classname="LM-59c-8 - Archive after failing all samples in the fourth protocol">
    </testcase>
    <testcase name="59c - archive worksheets with multiple sample protocols &quot;after all&quot; hook for &quot;LM-59c-8 - Archive after failing all samples in the fourth protocol&quot;" time="43.265" classname="&quot;after all&quot; hook for &quot;LM-59c-8 - Archive after failing all samples in the fourth protocol&quot;">
      <failure message="cy.exec(&apos;esp -s -P 443 -H chris.test.l7informatics.com -u admin@localhost -p L4b7R0cks! seed -f -d cypress/fixtures/apps/sample_sets/LM59cseed.yml&apos;) failed because the command exited with a non-zero code.

Pass {failOnNonZeroExit: false} to ignore exit code failures.

Information about the failure:
Code: 1

Stderr:
INFO:root:2020-06-26 16:14:31,441:Dropping SampleSheet: LM59-x c
INFO:root:2020-06-26 16:14:31,593:Dropping Experiment: LM59c-x
INFO:root:2020-06-26 16:14:32,894:Dropping Experiment: LM59c-1
Traceb...

Because this error occurred during a &apos;after all&apos; hook we are skipping the remaining tests in the current suite: &apos;59c - archive worksheets wi...&apos;" type="CypressError"><![CDATA[CypressError: cy.exec('esp -s -P 443 -H chris.test.l7informatics.com -u admin@localhost -p L4b7R0cks! seed -f -d cypress/fixtures/apps/sample_sets/LM59cseed.yml') failed because the command exited with a non-zero code.

Pass {failOnNonZeroExit: false} to ignore exit code failures.

Information about the failure:
Code: 1

Stderr:
INFO:root:2020-06-26 16:14:31,441:Dropping SampleSheet: LM59-x c
INFO:root:2020-06-26 16:14:31,593:Dropping Experiment: LM59c-x
INFO:root:2020-06-26 16:14:32,894:Dropping Experiment: LM59c-1
Traceb...

Because this error occurred during a 'after all' hook we are skipping the remaining tests in the current suite: '59c - archive worksheets wi...'
    at cypressErr (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:138036:9)
    at throwErr (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:137969:11)
    at Object.throwErrByPath (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:138017:3)
    at https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:125593:26
    at tryCatcher (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:164895:23)
    at Promise._settlePromiseFromHandler (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:162831:31)
    at Promise._settlePromise (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:162888:18)
    at Promise._settlePromise0 (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:162933:10)
    at Promise._settlePromises (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:163012:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:159620:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:159630:10)
    at Async.drainQueues (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:159504:14)]]></failure>
    </testcase>
  </testsuite>
</testsuites>