<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="185.88" tests="8" failures="1">
  <testsuite name="Root Suite" timestamp="2020-03-29T01:19:50" tests="0" file="cypress/integration/apps/sample_sets/LM58a.js" failures="0" time="0">
  </testsuite>
  <testsuite name="58a - archive worksheets with multiple sample protocols" timestamp="2020-03-29T01:19:50" tests="8" failures="1" time="185.88">
    <testcase name="58a - archive worksheets with multiple sample protocols LM-58a-1 - Archive after all samples are complete" time="47.915" classname="LM-58a-1 - Archive after all samples are complete">
    </testcase>
    <testcase name="58a - archive worksheets with multiple sample protocols LM-58a-2 - Archive after all samples fail in second protocol" time="11.12" classname="LM-58a-2 - Archive after all samples fail in second protocol">
    </testcase>
    <testcase name="58a - archive worksheets with multiple sample protocols LM-58a-3 - Archive after first sample fails in second protocol" time="17.681" classname="LM-58a-3 - Archive after first sample fails in second protocol">
    </testcase>
    <testcase name="58a - archive worksheets with multiple sample protocols LM-58a-4 - Archive after last sample fails in second protocol" time="17.312" classname="LM-58a-4 - Archive after last sample fails in second protocol">
    </testcase>
    <testcase name="58a - archive worksheets with multiple sample protocols LM-58a-5 - Archive after all samples fail in third protocol" time="13.36" classname="LM-58a-5 - Archive after all samples fail in third protocol">
    </testcase>
    <testcase name="58a - archive worksheets with multiple sample protocols LM-58a-6 - Archive after first sample fails in third protocol" time="17.637" classname="LM-58a-6 - Archive after first sample fails in third protocol">
    </testcase>
    <testcase name="58a - archive worksheets with multiple sample protocols LM-58a-7 - Archive after last sample fails in third protocol" time="18.079" classname="LM-58a-7 - Archive after last sample fails in third protocol">
    </testcase>
    <testcase name="58a - archive worksheets with multiple sample protocols LM-58a-8 - Archive after one sample fails in each sample protocol" time="21.388" classname="LM-58a-8 - Archive after one sample fails in each sample protocol">
    </testcase>
    <testcase name="58a - archive worksheets with multiple sample protocols &quot;after all&quot; hook for &quot;LM-58a-8 - Archive after one sample fails in each sample protocol&quot;" time="21.388" classname="&quot;after all&quot; hook for &quot;LM-58a-8 - Archive after one sample fails in each sample protocol&quot;">
      <failure message="cy.exec(&apos;esp  -P 8080 -H 127.0.0.1 -u admin@localhost -p admin seed -f -d cypress/fixtures/apps/sample_sets/LM58aseed.yml&apos;) failed because the command exited with a non-zero code.

Pass {failOnNonZeroExit: false} to ignore exit code failures.

Information about the failure:
Code: 1

Stderr:
INFO:root:2020-03-28 20:22:37,713:Saving data in Experiment LM58a-x for Protocol: Simple Protocol.
Traceback (most recent call last):
  File &quot;/Users/cj/bitrepos/esp/develop/bin/.venv/bin/esp&quot;, line...

Because this error occurred during a &apos;after all&apos; hook we are skipping the remaining tests in the current suite: &apos;58a - archive worksheets wi...&apos;" type="CypressError"><![CDATA[CypressError: cy.exec('esp  -P 8080 -H 127.0.0.1 -u admin@localhost -p admin seed -f -d cypress/fixtures/apps/sample_sets/LM58aseed.yml') failed because the command exited with a non-zero code.

Pass {failOnNonZeroExit: false} to ignore exit code failures.

Information about the failure:
Code: 1

Stderr:
INFO:root:2020-03-28 20:22:37,713:Saving data in Experiment LM58a-x for Protocol: Simple Protocol.
Traceback (most recent call last):
  File "/Users/cj/bitrepos/esp/develop/bin/.venv/bin/esp", line...

Because this error occurred during a 'after all' hook we are skipping the remaining tests in the current suite: '58a - archive worksheets wi...'
    at cypressErr (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:138036:9)
    at throwErr (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:137969:11)
    at Object.throwErrByPath (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:138017:3)
    at http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:125593:26
    at tryCatcher (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:164895:23)
    at Promise._settlePromiseFromHandler (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162831:31)
    at Promise._settlePromise (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162888:18)
    at Promise._settlePromise0 (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162933:10)
    at Promise._settlePromises (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:163012:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159620:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159630:10)
    at Async.drainQueues (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159504:14)]]></failure>
    </testcase>
  </testsuite>
</testsuites>